---
title: "proposal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Team Members

* Molly Buckler

* Armando Castillo

* Binaya Shrestha

* Dongming Li

* John Langenwalter

* Muhamad-Imran-Bin Maszeri



## Data set

### Links: 

* https://docs.opendata.aws/noaa-ghcn-pds/readme.html (Weather data)

* https://data.cdc.gov/dataset/LymeDisease_9211_county/smai-7mz9 (Lyme disease data)




## Data set overview

* Weather data

  * Contains the max and min temp. and precipitation rates for any given day.
  

* Lyme disease data

  * Contains confirmed cases of Lyme disease within four year spans. The years that it spans are 1992-1996, 1997-2001, 2002-2006, and 2007-2011.




## Project plan

* We will average the weather data and use it to compare to the Lyme disease data set. We will also use the individual data sets along with the averaged weather data to answer the questions below.

* Questions:

  * Is there any association with the rate of Lyme disease and the changes to temperature?
  
  * Is there any association with the rate of Lyme disease and the changes to precipitation?

  * Has Lyme disease increased from 1992?
  
  * What changes have happened to the rate of precipitation?
  
  * What changes have happened to the average temperature?
  
  * Which states have the highest rate of Lyme Disease?
  
  * Does the Lyme Disease rate in the states influenced by the weather?
